#!/usr/bin/with-contenv bash

if ! grep -q 'Version 2022/05/16' /config/nginx/site-confs/default.conf; then
    cp /defaults/default.conf /config/nginx/site-confs/default.conf
fi

if [ ! -f "/config/nginx/http-confs/real-ip.conf" ]; then
    cp /defaults/real-ip.conf /config/nginx/http-confs/real-ip.conf
fi

if [ ! -f "/config/config.json" ]; then
    cp /defaults/config.json /config/config.json
fi

if [ ! -f "/app/twitfix/config.json" ]; then
    ln -s /config/config.json /app/twitfix/config.json
fi

if [ ! -f "/config/twitfix.ini" ]; then
    cp /defaults/twitfix.ini /config/twitfix.ini
fi

TWIT_CONF=(
ACCESS_SECRET
ACCESS_TOKEN
API_KEY
API_SECRET
APPNAME
COLOR
DATABASE
LINK_CACHE
METHOD
URL
)

function insert_config() {
    if grep -E "^$1 = " /config/config.json &> /dev/null; then
        sed -i -E "s|^$1 = .*\$|$1 = $2|" /config/config.json
    else
        echo "$1 = $2" >> /config/config.json
    fi
}

for CONF in "${TWIT_CONF[@]}"; do
    if [[ -n "${!CONF}" ]]; then
        sed -i -E "s|$CONF|${!CONF}|" /config/config.json
    fi
done

chown -R abc:abc \
    /app \
    /config